from django.urls import path
from .views import (
    pdf_team_sport_main_list_students,
    pdf_team_sport_phase_list_students,
    pdf_dde_individual_sport_list_students,
    pdf_team_sport_main_lists_school,
    pdf_team_sport_main_lists_sport,
    pdf_team_sport_phase_lists_school,
    pdf_team_sport_phase_lists_sport,
    pdf_individual_sport_lists_school,
    pdf_individual_sport_lists_sport,
    pdf_individual_sports_group_phase,
    pdf_individual_sports_group_phase_preview,
    pdf_individual_sports_groups_phases,
    pdf_school_registrations,
    pdf_school_registration,
)

app_name = 'pdfs'

urlpatterns = [
    path('pdfs/team_sport_main_list_students/<int:pk>/', pdf_team_sport_main_list_students,
         name='pdf_team_sport_main_list_students'),
    path('pdfs/team_sport_phase_list_students/<int:pk>/', pdf_team_sport_phase_list_students,
         name='pdf_team_sport_phase_list_students'),
    path('pdfs/dde_individual_sport_list_students/<int:pk>/<str:phase>/', pdf_dde_individual_sport_list_students,
         name='pdf_dde_individual_sport_list_students'),
    path('pdfs/team_sport_main_lists_school/', pdf_team_sport_main_lists_school,
         name='pdf_team_sport_main_lists_school'),
    path('pdfs/team_sport_main_lists_sport/', pdf_team_sport_main_lists_sport,
         name='pdf_team_sport_main_lists_sport'),
    path('pdfs/team_sport_phase_lists_school/', pdf_team_sport_phase_lists_school,
         name='pdf_team_sport_phase_lists_school'),
    path('pdfs/team_sport_phase_lists_sport/', pdf_team_sport_phase_lists_sport,
         name='pdf_team_sport_phase_lists_sport'),
    path('pdfs/individual_sport_lists_school/', pdf_individual_sport_lists_school,
         name='pdf_individual_sport_lists_school'),
    path('pdfs/individual_sport_lists_sport/', pdf_individual_sport_lists_sport,
         name='pdf_individual_sport_lists_sport'),
    path('pdfs/individual_sports_group_phase/<int:pk>/', pdf_individual_sports_group_phase,
         name='pdf_individual_sports_group_phase'),
    path('pdfs/individual_sports_group_phase/<int:pk>/preview/', pdf_individual_sports_group_phase_preview,
         name='pdf_individual_sports_group_phase_preview'),
    path('pdfs/individual_sports_groups_phases/', pdf_individual_sports_groups_phases,
         name='pdf_individual_sports_groups_phases'),
    path('pdfs/school_registrations/', pdf_school_registrations,
         name='pdf_school_registrations'),
    path('pdfs/school_registration/<int:pk>/', pdf_school_registration,
         name='pdf_school_registration'),
]
