# Generated by Django 5.1.2 on 2024-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstate',
            name='active_sch_year',
            field=models.CharField(default='2024-2025', max_length=10, verbose_name='Ενεργό Σχολικό Έτος'),
        ),
    ]
