from django.urls import path
from .views import (
    home,
    AppStateModeToggleView,
    AppStateSchoolsEnabledToggleView,
    SchoolRegistrationView,
    SchoolRegistrationSubmitView,
    TeamSportMainListsView,
    TeamSportMainListCreateView,
    TeamSportMainListDeleteView,
    TeamSportMainListUpdateView,
    TeamSportMainListSubmitView,
    TeamSportMainListStudentsView,
    StudentForTeamSportMainListCreateView,
    StudentForTeamSportMainListUpdateView,
    StudentForTeamSportMainListDeleteView,
    TeamSportPhaseListsView,
    TeamSportPhaseListCreateView,
    TeamSportPhaseListDeleteView,
    TeamSportPhaseListUpdateView,
    TeamSportPhaseListSubmitView,
    TeamSportPhaseListStudentsView,
    IndividualSportsGroupPhaseListView,
    IndividualSportsGroupPhaseCreateView,
    IndividualSportsGroupPhaseDeleteView,
    IndividualSportsGroupPhaseUpdateView,
    IndividualSportsGroupPhaseSubmitView,
    IndividualSportListsView,
    IndividualSportListCreateView,
    IndividualSportListDeleteView,
    IndividualSportListUpdateView,
    IndividualSportListStudentsView,
    StudentForIndividualSportListCreateView,
    StudentForIndividualSportListUpdateView,
    StudentForIndividualSportListDeleteView,
    DDE_SchoolRegistrationsView,
    DDE_TeamSportMainListsView,
    DDE_TeamSportPhaseListsView,
    DDE_IndividualSportListsView,
    DDE_IndividualSportsGroupsPhasesView,
    TeamSportMainListUnlockView,
    TeamSportPhaseListUnlockView,
    IndividualSportsGroupPhaseUnlockView,
    dde_lists_for_printing,
    SchoolRegistrationUnlockView
)

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),

    path('school/school_registration/', SchoolRegistrationView.as_view(), name='school_registration'),
    path('school/school_registration/submit/', SchoolRegistrationSubmitView.as_view(),
         name='submit_school_registration'),
    #
    #  urls for School and the Team Sport Main Lists
    #
    path('school_tsml/', TeamSportMainListsView.as_view(), name='team_sport_main_lists'),
    path('school_tsml/create/', TeamSportMainListCreateView.as_view(),
         name='create_team_sport_main_list'),
    path('school_tsml/<int:pk>/delete/', TeamSportMainListDeleteView.as_view(),
         name='delete_team_sport_main_list'),
    path('school_tsml/<int:pk>/update/', TeamSportMainListUpdateView.as_view(),
         name='update_team_sport_main_list'),
    path('school_tsml/<int:pk>/submit/', TeamSportMainListSubmitView.as_view(),
         name='submit_team_sport_main_list'),
    path('school_tsml/<int:pk>/', TeamSportMainListStudentsView.as_view(),
         name='team_sport_main_list_students'),
    path('school_tsml/<int:team_sport_ml_pk>/create_student/',
         StudentForTeamSportMainListCreateView.as_view(),
         name='create_student_for_team_sport_main_list'),
    path('school_tsml/<int:team_sport_ml_pk>/<int:pk>/update',
         StudentForTeamSportMainListUpdateView.as_view(),
         name='update_student_for_team_sport_main_list'),
    path('school_tsml/<int:team_sport_ml_pk>/<int:pk>/delete',
         StudentForTeamSportMainListDeleteView.as_view(),
         name='delete_student_for_team_sport_main_list'),

    #
    #  urls for School and the Team Sport Phase Lists
    #
    path('school_tspl/', TeamSportPhaseListsView.as_view(), name='team_sport_phase_lists'),
    path('school_tspl/create/', TeamSportPhaseListCreateView.as_view(),
         name='create_team_sport_phase_list'),
    path('school_tspl/<int:pk>/delete/', TeamSportPhaseListDeleteView.as_view(),
         name='delete_team_sport_phase_list'),
    path('school_tspl/<int:pk>/update/', TeamSportPhaseListUpdateView.as_view(),
         name='update_team_sport_phase_list'),
    path('school_tspl/<int:pk>/submit/', TeamSportPhaseListSubmitView.as_view(),
         name='submit_team_sport_phase_list'),
    path('school_tspl/<int:pk>/', TeamSportPhaseListStudentsView.as_view(),
         name='team_sport_phase_list_students'),

    #
    #  urls for School and the Individual Sport Lists
    #
    path('school_isgp/', IndividualSportsGroupPhaseListView.as_view(), name='individual_sports_groups_phases'),
    path('school_isgp/create/', IndividualSportsGroupPhaseCreateView.as_view(),
         name='create_individual_sports_group_phase'),
    path('school_isgp/<int:pk>/', IndividualSportListsView.as_view(), name='individual_sports_lists'),
    path('school_isgp/<int:pk>/delete/', IndividualSportsGroupPhaseDeleteView.as_view(),
         name='delete_individual_sports_group_phase'),
    path('school_isgp/<int:pk>/update/', IndividualSportsGroupPhaseUpdateView.as_view(),
         name='update_individual_sports_group_phase'),
    path('school_isgp/<int:pk>/submit/', IndividualSportsGroupPhaseSubmitView.as_view(),
         name='submit_individual_sports_group_phase'),
    path('school_isgp/<int:pk>/create_individual_sport_list/', IndividualSportListCreateView.as_view(),
         name='create_individual_sport_list'),

    path('school_isl/<int:pk>/delete/', IndividualSportListDeleteView.as_view(),
         name='delete_individual_sport_list'),
    path('school_isl/<int:pk>/update/', IndividualSportListUpdateView.as_view(),
         name='update_individual_sport_list'),
    path('school_isl/<int:pk>/', IndividualSportListStudentsView.as_view(),
         name='individual_sport_list_students'),
    path('school_isl/<int:individual_sport_list_pk>/create_student/',
         StudentForIndividualSportListCreateView.as_view(),
         name='create_student_for_individual_sport_list'),
    path('school_isl/<int:individual_sport_list_pk>/<int:pk>/update',
         StudentForIndividualSportListUpdateView.as_view(),
         name='update_student_for_individual_sport_list'),
    path('school_isl/<int:individual_sport_list_pk>/<int:pk>/delete',
         StudentForIndividualSportListDeleteView.as_view(),
         name='delete_student_for_individual_sport_list'),

    #
    #  urls for DDE
    #
    path('dde/school_registrations/', DDE_SchoolRegistrationsView.as_view(), name='dde_school_registrations'),
    path('dde/team_sport_main_lists/', DDE_TeamSportMainListsView.as_view(), name='dde_team_sport_main_lists'),
    path('dde/team_sport_phase_lists/', DDE_TeamSportPhaseListsView.as_view(), name='dde_team_sport_phase_lists'),
    path('dde/individual_sport_lists/', DDE_IndividualSportListsView.as_view(), name='dde_individual_sport_lists'),
    path('dde/individual_sports_groups_phases/', DDE_IndividualSportsGroupsPhasesView.as_view(),
         name='dde_individual_sports_groups_phases'),
    path('dde/team_sport_main_list/<int:pk>/unlock/', TeamSportMainListUnlockView.as_view(),
         name='unlock_team_sport_main_list'),
    path('dde/team_sport_phase_list/<int:pk>/unlock/', TeamSportPhaseListUnlockView.as_view(),
         name='unlock_team_sport_phase_list'),
    path('dde/individual_sports_groups_phases/<int:pk>/unlock/', IndividualSportsGroupPhaseUnlockView.as_view(),
         name='unlock_individual_sports_groups_phases'),
    path('dde/lists_for_printing/', dde_lists_for_printing, name='dde_lists_for_printing'),
    path('dde/toggle_mode/', AppStateModeToggleView.as_view(), name='dde_toggle_mode'),
    path('dde/toggle_schools_enabled/', AppStateSchoolsEnabledToggleView.as_view(), name='dde_toggle_schools_enabled'),
    path('dde/school_registration/<int:pk>/unlock/', SchoolRegistrationUnlockView.as_view(),
         name='unlock_school_registration'),
]
