name: Build and Push to DockerHub

on:
  push:
    branches: [ "main" ]  # Κάθε push στο main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./unzipped/hercules-main/Dockerfile
          push: true
          tags: igaidaros/hercules:latest

