name: Unzip File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip file
        run: unzip hercules-main.zip -d unzipped/

      - name: Commit unzipped contents
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add unzipped/
          git commit -m "Add unzipped files" || echo "Nothing to commit"
      - name: Set up Git credentials
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Push changes
        run: git push
